---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r}
rm(list=ls())
library(knitr)
library(xtable)
library(dplyr)
setwd("~/Software/FCPC/stats")
source("~/Software/FCPC/stats/plotting_funcs.R")
BWRES=1000
POINTSIZE = 35
CEX_AXIS = 70
CEX_TITLE = 90
CEX_LINE = 3
CEX_TEXT = 50

OUTPUT_DIR = "~/Data/NSPN/results/"

#module_labels_ = read.table('~/Data/NSPN/templates/module_table.csv')$Name
#all_module_labels_ = c(module_labels_, "All")
#fdr_correct_ = seq(length(all_module_labels_)) # choose between correcting all or only some

alpha = 0.05

FIGS_DIR = OUTPUT_DIR

```


Motion parameters

```{r eval = F}


motion_parameters = function(DIR_ICA_ME){
  print(DIR_ICA_ME)
  FILE_DOF = file.path(DIR_ICA_ME, 'meica_DOF_nom.txt')
  FILE_FD = file.path(DIR_ICA_ME, 'fd.txt')
  FILE_DVARS = file.path(DIR_ICA_ME, 'dvars.txt')
  FILE_SUBJECTS = file.path(DIR_ICA_ME, 'subjects.txt')
  meica_dof = read.table(FILE_DOF)
  fd = read.table(FILE_FD)
  fd.max = cbind(fd[1], apply(fd[-c(1,2)], 1, max))
  fd = cbind(fd[1], rowMeans(fd[-c(1,2)])) #mean
  colnames(fd) =  colnames(fd.max) = c("Subject", "FD")
  dvars = read.table(FILE_DVARS)
  dvars = cbind(fd[1], rowMeans(dvars[-c(1,2)]))

  par(mfrow = c(2, 2))
  hist(fd[, 2], 30, main = "Mean fd")
  hist(fd.max[, 2], 30, main = "Max fd")
  hist(dvars[, 2], 30, main = "Mean dvars")
  hist(meica_dof[, 2], 30, main = "Mean dof")
  print(subset(fd, FD > 0.3))
  print(subset(fd.max, FD > 1.3))
  return(fd)
}
# baseline
fd.1 = motion_parameters("~/Data/NSPN/ICA_ME/nspn_ME/ica200.gica/")

#follow up
fd.2 = motion_parameters("~/Data/NSPN/ICA_ME/nspn_ME_fu/ica200.bsl.gica/")

fd.12 = merge(fd.1, fd.2, by = "Subject",, suffixes = c(".1", ".2"))
plot(FD.2 ~ FD.1, data = fd.12, xlim = c(0, 0.5), ylim = c(0, 0.5))
abline(0, 1)
cor.test(fd.12$FD.2, fd.12$FD.1)

```
```{r eval = F}
# baseline
DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_200iters_democorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
rho.bsl = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-demo_corrected_baseline_10iters')
# different nsamples
load(RESULTS_FILE)
j = 8
results = var.network.results[[j]]
z = fisherz(results$cor.test$perm)
shapiro.test(z)
qqnorm(z/sd(z))
abline(0, 1)

sigma = sd(z[-1])

pvalue = NULL
nsamps = seq(30, 50, 10)
for(i in seq(length(nsamps))){
  nsamp = nsamps[i]
  z.down = sample(z, nsamp, replace = F)
  sigma.down = sd(z.down)
  pvalue[i] = 0.5*erfc(z[1]/sigma.down)

}

plot(nsamps, pvalue, pch = 20, type = 'b', ylim = range(c(results$cor.test$p.value, pvalue)))
abline(results$cor.test$p.value, 0)

hist(z, 100, probability = T)
lines(x <- seq(-.5, .5, .01) , dnorm(x, 0, sigma), type = 'l', col = 'red', lwd = 2)
lines(x <- seq(-.5, .5, .01) , dnorm(x, 0, sigma.down), type = 'l', col = 'red')

# across modules
nsamp = 50

pvalue = pvalue.true = NULL
for (j in seq(length(var.network.results))){
results = var.network.results[[j]]
z = fisherz(results$cor.test$perm)
  print(shapiro.test(z))
  qqnorm(z/sd(z))
  abline(0, 1)
  z.down = sample(z, nsamp, replace = F)
  sigma.down = sd(z.down)
  pvalue[j] = 0.5*erfc(z[1]/sigma.down)
  pvalue.true[j] = results$cor.test$p.value
}

plot(log(pvalue.true, 10), log(pvalue, 10), pch = 20)
abline(0, 1)

```

Different number of iterations
```{r, fig.width = 20, width = 1000, eval = F}

# baseline
DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_1iters_democorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
rho.bsl = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-demo_corrected_baseline_1iters')



DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_10iters_democorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
rho.bsl = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-demo_corrected_baseline_10iters')

RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.fu"), "data.RData")
rho.fu = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-demo_corrected_followup_10iters')


DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_20iters_democorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
rho.bsl = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-demo_corrected_baseline_20iters')

RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.fu"), "data.RData")
rho.fu = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-demo_corrected_followup_20iters')

DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_20iters_democorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
rho.bsl = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-notagecorrected_baseline_20iters')

RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.fu"), "data.RData")
rho.fu = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-notagecorrected_followup_20iters')

# baseline
# DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_100iters_democorrected_")
# RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
# RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
# rho.bsl = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
#            myfigname = 'Accuracy-decAc-demo_corrected_baseline_100iters')


DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_150iters_democorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
rho.bsl = plot_intervals(RESULTS_FILE, "d\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-demo_corrected_baseline_150iters')



```


Decision acuity, non-depressed sample


```{r, fig.width = 20, width = 1000 }

print("------------------------------")
print("Demo corrected")
print("------------------------------")

# baseline
DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_200iters_democorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
rho.d.bsl = plot_intervals(RESULTS_FILE, "d at baseline\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-demo_corrected_baseline')


# follow-up
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.fu"), "data.RData")
rho.d.fu = plot_intervals(RESULTS_FILE, "d at follow-up\n (Controlling for all covariates except IQ)", 
           myfigname = 'Accuracy-decAc-demo_corrected_followup')


# follow-up, selecting
plot_intervals(RESULTS_FILE, "d at follow-up\n (Controlling for all covariates except IQ)", 
             myfigname = 'Accuracy-decAc-demo_corrected_followup_selection', selection = rho.d.bsl$network[rho.d.bsl$fdrp < 0.05])


print("------------------------------")
print("Cognitive corrected")
print("------------------------------")
DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_200iters_cogcorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
rho.d2.bsl = plot_intervals(RESULTS_FILE, "d at baseline\n (Controlling for all covariates including IQ)", myfigname = 'Accuracy-decAc-IQ_corrected')

```

IQ, non-depressed sample

```{r, fig.width = 20, width = 1000 }
if (F){
print("------------------------------")
print("Demo corrected")
print("------------------------------")
DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_100iters_democorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "IQcomp.bsl"), "data.RData")
rho.I.bsl = plot_intervals(RESULTS_FILE, "IQ at baseline \n (Controlling for all covariates except d)", myfigname = 'Accuracy-IQcomp-demo_corrected')
}

print("------------------------------")
print("Cognitive corrected")
print("------------------------------")
DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_200iters_cogcorrected_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "IQcomp.bsl"), "data.RData")
rho.I2.bsl =  plot_intervals(RESULTS_FILE, "IQ at baseline\n (Controlling for all covariates including d)", myfigname = 'Accuracy-IQcomp-decAc_corrected')

```

Make a table

```{r}
allresults = cbind(rho.d.bsl[c("network", "mean", "p.approx", "fdrp", "sig")], rho.d.fu[c("mean", "p.approx", "fdrp", "sig")],
             rho.d2.bsl[c("mean", "p.approx", "fdrp", "sig")], rho.I2.bsl[c("mean", "p.approx", "fdrp", "sig")])

ff = function(x){
  ifelse(!is.na(as.numeric(x)),   
         ifelse (abs(as.numeric(x)) >= 0.001,  
                 format(round(as.numeric(x), 3), digits = 3, nsmall= 3, scientific = F),
                 ifelse(abs(as.numeric(x)) > 1e-6 ,
                format(as.numeric(x), digits = 3, nsmall= 3, scientific = T), "< 1e-6")), 
         x)
  
}

View(
    apply(allresults, c(1, 2), ff)
)
```

# plot
```{r}
stophere
FIGS_DIR = OUTPUT_DIR

plot_combinations(rbind(rho.bsl, rho.fu) %>% arrange(network, timepoint), "d", myfigname = 'Accuracy-decAc')

plot_combinations(rbind(rho.bsl.democorrected, rho.fu.democorrected) %>% arrange(network, timepoint), "d\n (Controlling for all covariates except IQ)", myfigname = 'Accuracy-decAc-demo_corrected')

plot_combinations(rbind(rho.bsl.IQcorrected, rho.fu.IQcorrected) %>% arrange(network, timepoint), "d\n (Controlling for all covariates including IQ)", myfigname = 'Accuracy-decAc-IQ_corrected')

```


IQ composite, non-depressed sample


```{r}
print("------------------------------")
print("Baseline")
print("------------------------------")


DIR_PREFFIX = paste0("prediction_data_nondep_Power_ledoit_LOOCV", NITER, "iters_")

RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "IQcomp.bsl"), "data.RData")
load(RESULTS_FILE)
source("~/Software/FCPC/stats/prediction_funcs.R")
rho.bsl = statstodf(var.network.results, "bsl")


# replace correlations by corrected versions

print("------------------------------")
print("Controlling for demographics")
print("------------------------------")

controlfor = c("brain_vol", "fd", "UCL.1", "CBU.1", "meica_dof")

var.corrected.network.results = NULL

for (i in seq(length(var.network.results))){
  var.corrected.network.results[[i]] = do_correction(DIR_ICA_ME, 
                                                     var.network.results[[i]], 
                                                     data.pars,
                                                     controlfor = controlfor)
}


rho.bsl.democorrected = statstodf(var.corrected.network.results, "bsl.democorrected")


print("------------------------------")
print("Controlling for d")
print("------------------------------")


controlfor = c("brain_vol", "fd", "meica_dof",  "UCL.1", "CBU.1", "decAc.bsl")

var.corrected.network.results = NULL


for (i in seq(length(var.network.results))){
  var.corrected.network.results[[i]] = do_correction(DIR_ICA_ME, 
                                                     var.network.results[[i]], 
                                                     data.pars,
                                                     controlfor = controlfor)
}


rho.bsl.dcorrected = statstodf(var.corrected.network.results, "bsl.dcorrected")

```

```{r}
print("------------------------------")
print("Follow-up")
print("------------------------------")


RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "IQcomp.fu"), "data.RData")
load(RESULTS_FILE)
source("~/Software/FCPC/stats/prediction_funcs.R")
rho.fu = statstodf(var.network.results, "fu")
  
print(var.prediction.results$cor.test.twotailed)


# replace correlations by corrected versions

print("------------------------------")
print("Controlling for demographics")
print("------------------------------")

controlfor = c("brain_vol", "fd", "UCL.2", "CBU.2", "meica_dof")

var.corrected.network.results = NULL

for (i in seq(length(var.network.results))){
  var.corrected.network.results[[i]] = do_correction(DIR_ICA_ME, 
                                                     var.network.results[[i]], 
                                                     data.pars,
                                                     controlfor = controlfor)
}


rho.fu.democorrected = statstodf(var.corrected.network.results, "fu.democorrected")


print("------------------------------")
print("Controlling for IQ")
print("------------------------------")


controlfor = c("brain_vol", "fd", "meica_dof",  "UCL.2", "CBU.2", "decAc.fu")

var.corrected.network.results = NULL


for (i in seq(length(var.network.results))){
  var.corrected.network.results[[i]] = do_correction(DIR_ICA_ME, 
                                                     var.network.results[[i]], 
                                                     data.pars,
                                                     controlfor = controlfor)
}


rho.fu.dcorrected = statstodf(var.corrected.network.results, "fu.dcorrected")

```

# plot
```{r}
FIGS_DIR = OUTPUT_DIR

plot_combinations(rbind(rho.bsl, rho.fu) %>% arrange(network, timepoint), "d", myfigname = 'Accuracy-IQcomp')

plot_combinations(rbind(rho.bsl.democorrected, rho.fu.democorrected) %>% arrange(network, timepoint), "IQ\n (Controlling for all covariates except d)", myfigname = 'Accuracy-IQcomp-demo_corrected')

plot_combinations(rbind(rho.bsl.dcorrected, rho.fu.dcorrected) %>% arrange(network, timepoint), "IQ\n (Controlling for all covariates including d)", myfigname = 'Accuracy-IQcomp-decAc_corrected')

```



```{r}
STOPHERE
----------------------------------



RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "IQcomp.bsl"), "data.RData")
load(RESULTS_FILE)
source("~/Software/FCPC/stats/prediction_funcs.R")
rho.bsl = statstodf(var.network.results, "bsl")

# replace correlations by corrected versions

print("------------------------------")
print("Controlling for demographics")
print("------------------------------")


controlfor = c("brain_vol", "fd", "meica_dof",  "UCL.1", "CBU.1")

var.corrected.network.results = NULL

for (i in seq(length(var.mediation.network.results))){
  var.corrected.network.results[[i]] = do_correction(DIR_ICA_ME, 
                                                     var.network.results[[i]], 
                                                     demo.pars,
                                                     controlfor = controlfor)
}





print("------------------------------")
print("Controlling for decAc")
print("------------------------------")


controlfor = c("brain_vol", "fd", "meica_dof",  "UCL", "CBU", "decAc")

var.corrected.network.results = NULL

for (i in seq(length(var.mediation.network.results))){
  var.corrected.network.results[[i]] = do_correction(DIR_ICA_ME, 
                                                     var.mediation.network.results[[i]], 
                                                     demo.pars,
                                                     controlfor = controlfor)
}

var.corrected.results =  do_correction(DIR_ICA_ME, 
                                       var.mediation.results, 
                                       demo.pars,
                                       controlfor = controlfor)

print(var.corrected.results$cor.test.twotailed)

plot_combinations(var.corrected.network.results, var.corrected.results$cor.test.twotailed, module_labels_, "IQ\n (Controlling for all covariates including d)", myfigname = 'Accuracy-decAc_corrected')


```

```{r}
if (F){

print("------------------------------")
print("Demo corrected")
print("------------------------------")

# split in independent groups
DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_100iters_democorrected_split_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.bsl"), "data.RData")
load(RESULTS_FILE)
rho.bsl = statstodf(var.network.results, "bsl") %>% arrange(network, group_name)
cor.perm.bsl = sapply(var.network.results, function(x) x$cor.test$perm)
rm(var.network.results)

DIR_PREFFIX = paste0("prediction_data_nondep_ICA_ridge_20folds_100iters_democorrected_split_")
RESULTS_DIR = file.path(OUTPUT_DIR, DIR_PREFFIX) 
RESULTS_FILE = file.path(paste0(RESULTS_DIR, "decAc.fu"), "data.RData")
load(RESULTS_FILE)
rho.fu = statstodf(var.network.results, "fu") %>% arrange(network, group_name)
cor.perm.fu = sapply(var.network.results, function(x) x$cor.test$perm)
rm(var.network.results)

plot_combinations(rbind(rho.bsl, rho.fu), "d\n (Controlling for all covariates except IQ)", myfigname = 'Accuracy-decAc-demo_corrected-split', group = T)

# compare effects
cor.perm.bsl = cor.perm.bsl[, -ncol(cor.perm.bsl)]
cor.perm.fu = cor.perm.fu[, -ncol(cor.perm.fu)]
r.perm = sapply(seq(nrow(cor.perm.bsl)), function (i) cor.test(cor.perm.bsl[i, ], cor.perm.fu[i, ])$estimate)
pvalue = sum(r.perm[1] <= r.perm)/length(r.perm)

r.bsl = subset(rho.bsl, group_name == "bsl" & from != "All")$mean
r.fu = subset(rho.fu, group_name == "fu" & from != "All")$mean
print(cor.test(r.bsl, r.fu))

save_fig(figname = "GroupCorrelation-split", res = BWRES)

par(mfrow=c(1,1))
plot(r.bsl, r.fu, xlab = "Baseline r", ylab = "Follow-up r", pch = 20, col = "white" )
text(r.bsl, r.fu,
     labels = subset(rho.bsl, from != "All")$from)
abline(0, 1, lty = 2)
legend("topleft", legend = paste("r=", format(r.perm[1], digits = 2), 
                                 "p=", pvalue))
dev.off()
}

```
